ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS frame_system VARCHAR(255);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS frame_finish VARCHAR(255);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS lock_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS rh_hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS lh_hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS door_header_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS transom_header_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS hinge_door_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS latch_door_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS horizontal_transom_gutter_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS horizontal_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS vertical_transom_gutter_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS vertical_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS head_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN IF NOT EXISTS transom_head_perimeter_filler_id INTEGER REFERENCES door_parts(id);
