ALTER TABLE door_configurations ADD COLUMN frame_system VARCHAR(255);
ALTER TABLE door_configurations ADD COLUMN frame_finish VARCHAR(255);
ALTER TABLE door_configurations ADD COLUMN hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN lock_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN rh_hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN lh_hinge_jamb_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN door_header_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN transom_header_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN hinge_door_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN latch_door_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN horizontal_transom_gutter_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN horizontal_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN vertical_transom_gutter_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN vertical_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN head_transom_stop_id INTEGER REFERENCES door_parts(id);
ALTER TABLE door_configurations ADD COLUMN transom_head_perimeter_filler_id INTEGER REFERENCES door_parts(id);
