version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: fab_admin
      DB_USER: fab_admin
      DB_PASSWORD: fab_admin
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fab_admin
      POSTGRES_USER: fab_admin
      POSTGRES_PASSWORD: fab_admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data:
